project_id = "cavhogjsadmhdlrmeewr"

[functions.analyze-question]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.realtime-session]
verify_jwt = false

[functions.generate-arena-question]
verify_jwt = false

[functions.evaluate-arena-answer]
verify_jwt = false
